language: python
python:
  # FIXME: 3.7-dev requires the virtualenv env variable to run, but that breaks
  # 3.5, 3.6 installs.
  # See: https://github.com/pypa/pipenv/issues/1050
  - "3.7-dev"

env:
  - PIPENV_IGNORE_VIRTUALENVS=1  # Required by 3.7-dev job.

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest -vv
